name: nf-core-epitopeprediction-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=2.7.13
  - multiqc=1.7
  - snpsift=4.3.1t
  - csvtk=0.15.0
  - fred2=2.0.2
  - mhcflurry=1.2.4
  - mhcnuggets=2.2.0