name: nf-core-epitopeprediction-1.0dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=2.7.13
  - multiqc=1.6
  - snpsift=4.3.1t
  - csvtk=0.15.0
  - fred2=2.0.2

  # missing: netMHC, netMHCpan, netMHCII, netMHCIIpan